#Requires -Version 5
enum NET_FW_PROFILE_TYPE2_ {
    NET_FW_PROFILE2_DOMAIN = 1
    NET_FW_PROFILE2_PRIVATE = 2
    NET_FW_PROFILE2_PUBLIC = 4
    NET_FW_PROFILE2_ALL = 2147483647
}

enum NET_FW_ACTION_ {
    NET_FW_ACTION_BLOCK = 0
    NET_FW_ACTION_ALLOW = 1
    NET_FW_ACTION_MAX = 2
}

enum NET_FW_RULE_DIRECTION_ {
    NET_FW_RULE_DIR_IN = 0
    NET_FW_RULE_DIR_OUT = 1
    NET_FW_RULE_DIR_MAX = 2
}

enum NET_FW_IP_PROTOCOL_ {
    NET_FW_IP_PROTOCOL_ICMPv4 = 1
    NET_FW_IP_PROTOCOL_IGMP = 2
    NET_FW_IP_PROTOCOL_TCP = 6
    NET_FW_IP_PROTOCOL_UDP = 17
    NET_FW_IP_PROTOCOL_IPv6 = 41
    NET_FW_IP_PROTOCOL_IPv6ROUTE = 43
    NET_FW_IP_PROTOCOL_IPv6FRAG = 44
    NET_FW_IP_PROTOCOL_GRE = 47
    NET_FW_IP_PROTOCOL_ICMPv6 = 58
    NET_FW_IP_PROTOCOL_IPv6NONXT = 59
    NET_FW_IP_PROTOCOL_IPv6OPTS = 60
    NET_FW_IP_PROTOCOL_VRRP = 112
    NET_FW_IP_PROTOCOL_PGM = 113
    NET_FW_IP_PROTOCOL_L2TP = 115
    NET_FW_IP_PROTOCOL_ANY = 256
}

Get-ChildItem -Recurse $PSScriptRoot *.psm1 | ForEach-Object {
    if ( $_.FullName -ne $PSCommandPath ) {
        Import-Module $_.FullName
    }
}
Export-ModuleMember -Function *